grafana:
  extraEnvVars:
    - name: GF_SERVER_ROOT_URL
      value: "https://pp-commhub.nonprod.nb01.local/grafana"
    - name: GF_SERVER_SERVE_FROM_SUB_PATH
      value: "true"
  updateStrategy:
    type: Recreate
persistence:
  storageClass: gp2
smtp:
  enabled: true
  host: mail-gateway.infoftps.com:25
  skipVerify: true
ingress:
  enabled: true
  apiVersion: networking.k8s.io/v1
  hostname: pp-commhub.nonprod.nb01.local
  path: /grafana
  tls: true
