kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - extensions
      - batch
      - apps
      - autoscaling
      - '*'
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - bindings
      - componentstatuses
      - configmaps
      - deployments
      - deployments/scale
      - endpoints
      - events
      - pods
      - pods/attach
      - pods/binding
      - pods/eviction
      - pods/exec
      - pods/log
      - pods/portforward
      - pods/proxy
      - pods/status
      - podtemplates
      - secrets
      - serviceaccounts
      - services
      - services/proxy
      - services/status
      - ingresses
      - horizontalpodautoscalers
  - verbs:
      - '*'
    apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - podmonitors
