kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: list-custom-resources
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
