kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dashboard-read-only
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources:
      - bindings
      - componentstatuses
      - configmaps
      - deployments
      - endpoints
      - events
      - namespaces
      - pods
      - pods/status
      - pods/eviction
      - pods/log
      - pods/status
      - podtemplates
      - replicasets
      - serviceaccounts
      - services
      - services/status
      - ingress
      - cronjobs
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - monitoring.coreos.com
    resources:
      - '*'
